CXXFLAGS=-Wall -O3 -g
OBJECTS=main.cpp UIManager/UIManager.cpp
BINARIES=main

RGB_INCDIR=matrix/include
RGB_LIBDIR=matrix/lib
RGB_LIBRARY_NAME=rgbmatrix
RGB_LIBRARY=$(RGB_LIBDIR)/lib$(RGB_LIBRARY_NAME).a

ROTARY_INCDIR=rotary/include
ROTARY_LIBDIR=rotary/lib
ROTARY_LIBRARY_NAME=rotary
ROTARY_LIBRARY=$(ROTARY_LIBDIR)/lib$(ROTARY_LIBRARY_NAME).a

UIMANAGER_LIBDIR=UIManager/
UIMANAGER_INCDIR=UIManager/
UIMANAGER_LIBRARY_NAME=UIManager
UIMANAGER_LIBRARY=$(UIMANAGER_LIBDIR)/lib$(UIMANAGER_LIBRARY_NAME).a

UTILS_LIBDIR=UtilLib/
UTILS_INCDIR=UtilLib/
UTILS_LIBRARY_NAME=utils
UTILS_LIBRARY=$(UTILS_LIBDIR)/lib$(UTILS_LIBRARY_NAME).a

MAGICK_CXXFLAGS?=$(shell GraphicsMagick++-config --cppflags --cxxflags)
MAGICK_LDFLAGS?=$(shell GraphicsMagick++-config --ldflags --libs)

LDFLAGS+=-L$(RGB_LIBDIR) -l$(RGB_LIBRARY_NAME) \
	 -L$(ROTARY_LIBDIR) -l$(ROTARY_LIBRARY_NAME) \
	 -L$(UTILS_LIBDIR) -l$(UTILS_LIBRARY_NAME) \
	 -lrt -lm -lpthread $(MAGICK_CXXFLAGS) $(MAGICK_LDFLAGS)
         
	

all : main

main : $(OBJECTS) $(UIMANAGER_LIBDIR) $(RGB_LIBRARY) $(ROTARY_LIBRARY) $(UTILS_LIBRARY)
	$(CXX) $(CXXFLAGS) $(OBJECTS) -o $@ $(LDFLAGS)

$(RGB_LIBRARY): FORCE
	$(MAKE) -C $(RGB_LIBDIR)

$(ROTARY_LIBRARY): FORCE
	$(MAKE) -C $(ROTARY_LIBDIR)

$(UTILS_LIBRARY): FORCE
	$(MAKE) -C $(UTILS_LIBDIR)

clock.o : main.cpp

%.o : %.cpp
	$(CXX) -I$(UIMANAGER_INCDIR) -I$(ROTARY_INCDIR) -I$(RGB_INCDIR) -I$(UTILS_INCDIR) $(CXXFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECTS) $(BINARIES)
	$(MAKE) -C $(RGB_LIBDIR) clean
	$(MAKE) -C $(ROTARY_LIBDIR) clean
	$(MAKE) -C $(UTILS_LIBDIR) clean

FORCE:
.PHONY: FORCE
